[package]
name = "order_book-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.order_book]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.1"
